name: FPGA CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-and-sim:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install FPGA toolchain (yosys, nextpnr-ice40, icestorm, iverilog)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            yosys nextpnr-ice40 icestorm iverilog \
            python3 python3-pip
          python3 -m pip install --upgrade pip
          # We’ll use these later for the host CLI and plotting demos
          python3 -m pip install pyserial matplotlib

      - name: Show tool versions
        run: |
          yosys -V || true
          nextpnr-ice40 --version || true
          icepack -h 2>&1 | head -n 1 || true
          iceprog -h 2>&1 | head -n 1 || true
          iverilog -V || true
          python3 --version
          pip3 --version

      - name: Env check
        run: make env-check

      - name: Run simulations (no-op until testbenches exist)
        run: make sim
